export const T = {
  // 시스템 관련
  CHANGE_TOP_STYLE: "CHANGE_TOP_STYLE",

  // 회원 관련
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  LOGOUT: "LOGOUT",


  ADD_WORKSPACE: "ADD_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  GET_PROJECTS: "GET_PROJECTS",
  GET_WORKSPACE_DETAIL: "GET_WORKSPACE_DETAIL",
  CHANGE_WORKSPACE_ID: "CHANGE_WORKSPACE_ID",
  SEARCH_USER: "SEARCH_USER",

};
